# Generated by Django 5.1 on 2024-09-06 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_rename_catagory_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Trending',
            new_name='trending',
        ),
    ]
